Bump python version to 3.9
Replace rpm-py-installer with rpmdyn to fix CI failure. Bump to py39
because it failed with another error in py37:
AttributeError: 'TransactionSet' object has no attribute 'setKeyring'.